### ISSUE TITLE
PendingExports data cleared after Export Audit Drop file

### ISSUE THREAD

**Issue by Bob-Bradley** [lithnet/miis-powershell#37]
Hi @ryannewington ... this may not be a bug with the module, but I've noticed this weekend that after an export audit drop file is created on an export run profile ("and stop run" option), the Pending Exports attributes/dnattributes collection are cleared.  Can you verify this, and if so indicate if you think this is an MS bug (which rings a bell) or something you believe you can fix?  I updated your library today after I noticed the operations were showing as "None" for multivalue attribute changes, and appreciate the work you've done to fix that issue.
Cheers ... hope you're doing well.
Bob

**Comment by ryannewington** [comment]
Hey Bob. Good to hear from you! It certainly sounds like a sync engine thing. The module is just using WMI underneath. So if you can reproduce this using native WMI "Execute" call (which I suspect you will be able to), then that should make a less complicated case to log with MS, because you won't have to convince them that it's not the third party tool doing this 🤣
